# What is numpy?

* NumPy (Numerical Python) is a powerful library for numerical computing in Python, providing support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays.

* It enables efficient computation of mathematical operations such as linear algebra, Fourier transforms, and random number generation.

* NumPy's array operations are optimized and vectorized, making it faster than traditional Python lists for numerical computations.

* It serves as a fundamental library for data science, machine learning, and scientific computing due to its ease of use, performance, and broad ecosystem of extensions.

#  Array Creation

### 1. Using array(): Create an array from lists or tuples.

In [1]:
import numpy as np
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

### 2. Using zeros(): Create an array of zeros.

In [2]:
arr = np.ones((2, 3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

# Array Attributes

In NumPy, attributes refer to properties associated with NumPy arrays. These attributes provide useful information about the array's structure and its contents. Here are some of the key attributes:

### 1. ndarray.ndim

 The number of axes (dimensions) of the array.

In [3]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.ndim)

2


### 2. ndarray.shape
A tuple representing the dimensions of the array. For a matrix with n rows and m columns, the shape will be (n, m).

In [4]:
print(a.shape) 

(2, 3)


### 3. ndarray.size

The total number of elements in the array.

In [5]:
print(a.size)  

6


### 4. ndarray.dtype

n NumPy, ndarray.dtype refers to an attribute of the NumPy array object (ndarray) that specifies the data type of the elements stored in the array.

In [6]:
print(a.dtype)

int32


### 5. ndarray.itemsize

The size in bytes of each element in the array.

In [7]:
print(a.itemsize) 

4


### 6. ndarray.transpose

The transpose of the array.

In [8]:
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


# NumPy Data Types

A data type is a way to specify the type of data that will be stored in an array.

array1 = np.array([2, 4, 6]) # Here, the array1 array contains three integer elements, so the data type is Integer(int64)).

## NumPy Data Types:

NumPy offers a wider range of numerical data types than what is available in Python. Here's the list of most commonly used numeric data types in NumPy:

* int8, int16, int32, int64 - signed integer types with different bit sizes

* uint8, uint16, uint32, uint64 - unsigned integer types with different bit sizes

* float32, float64 - floating-point types with different precision levels

* complex64, complex128 - complex number types with different precision levels

### 1. To check the data type of a NumPy array, we can use the dtype attribute.

In [9]:
import numpy as np

# create an array of integers 
array1 = np.array([2, 4, 6])

# check the data type of array1
print(array1.dtype)

int32


### 2. Creating NumPy Arrays With a Defined Data Type

In NumPy, we can create an array with a defined data type by passing the dtype parameter while calling the np.array() function. For example,

In [10]:
import numpy as np
# create an array of 32-bit integers
array1 = np.array([1, 3, 7], dtype='int32')
print(array1, array1.dtype)

[1 3 7] int32


## NumPy Type Conversion

In NumPy, we can convert the data type of an array using the astype() method. For example,

In [11]:
import numpy as np
# create an array of integers
int_array = np.array([1, 3, 5, 7])
# convert data type of int_array to float
float_array = int_array.astype('float')
# print the arrays and their data types
print(int_array, int_array.dtype)
print(float_array, float_array.dtype)

[1 3 5 7] int32
[1. 3. 5. 7.] float64


# Array Methods

### 1. Reshaping Arrays:

arr.reshape(): Gives a new shape to an array without changing its data.

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape((2, 3))
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

### 2. Array Operations:

 * np.add(): Adds two arrays element-wise.

In [13]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.add(arr1, arr2)
result

array([5, 7, 9])

* np.multiply(): Multiplies two arrays element-wise.

In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.multiply(arr1, arr2)
result

array([ 4, 10, 18])

### 3. Array Aggregations:

* np.sum(): Sum of array elements.

In [15]:
arr = np.array([1, 2, 3, 4])
total = np.sum(arr)
total

10

* np.mean(): Mean of array elements.

In [16]:
arr = np.array([1, 2, 3, 4])
mean_value = np.mean(arr)
mean_value

2.5

### 4. Indexing and Slicing:

* arr[1:3]: Slices the array from index 1 to 3 (exclusive).

In [17]:
arr = np.array([1, 2, 3, 4, 5])
sliced_arr = arr[1:3]
sliced_arr

array([2, 3])

* arr[0, 1]: Indexing an element.

In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
element = arr[0, 1] 
element

2

### 5. Transposing Arrays:



* arr.T: Transposes the array.


In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr = arr.T
transposed_arr

array([[1, 4],
       [2, 5],
       [3, 6]])

### 6. Splitting Arrays:


* np.split(): Splits an array into multiple sub-arrays.

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.split(arr, 3)
split_arr

[array([1, 2]), array([3, 4]), array([5, 6])]

# Arange

The np.arange function in NumPy is used to create arrays with regularly spaced values within a given interval. It is similar to the built-in Python function range but returns a NumPy array.

* start (optional): The starting value of the sequence. The default is 0.

* stop: The end value of the sequence. This value is not included in the array.


* step (optional): The spacing between values. The default is 1.

* dtype (optional): The desired data-type for the array.

### 1. Basic Usage:

In [21]:
import numpy as np
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


### 2. Specifying Start and Stop:



In [22]:
arr = np.arange(2, 7)
print(arr)

[2 3 4 5 6]


### 3. Specifying Step:



In [23]:
arr = np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


### 4. Using Float Values:

In [24]:
arr = np.arange(0, 1, 0.2)
print(arr)

[0.  0.2 0.4 0.6 0.8]


# Random

NumPy's random module provides various functions to generate random numbers and perform random sampling. It can be used for tasks like generating random numbers, shuffling arrays, and sampling from statistical distributions.



### 1.  To generate random numbers

np.random.rand(): Generates random numbers in a given shape from a uniform distribution over [0, 1).

In [25]:
import numpy as np
random_numbers = np.random.rand(3)
print(random_numbers)

[0.73083667 0.66756161 0.49731412]


### 2. To generate random numbers

np.random.randint(low, high=None, size=None, dtype=int)


In [26]:
random_integers = np.random.randint(1, 10, size=5)
print(random_integers)

[7 6 5 6 9]


### 3. To generate Random numbers by choice

numpy.random.choice: Generates a random sample from a given 1D array.

In [27]:
# Generate a random sample of size 3 from a given array
arr = np.array([1, 2, 3, 4, 5])
sample = np.random.choice(arr, size=3)
print("Random sample:", sample)

Random sample: [5 1 1]


### 4. To shuffle the elements of an array

numpy.random.shuffle:numpy.random.shuffle

In [28]:
# Shuffle elements of an array
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print("Shuffled array:", arr)

Shuffled array: [3 2 5 1 4]


### 5. Permutations of random elements

* Shuffling Arrays

Shuffle means changing arrangement of elements in-place. i.e. in the array itself.

In [29]:
from numpy import random
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)
print(arr)

[3 2 4 1 5]


* Generating Permutation of Arrays

In [30]:
from numpy import random
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(random.permutation(arr))

[1 5 4 3 2]


# Mutability

In the context of NumPy arrays, mutability refers to whether the contents of an array can be modified after it has been created. NumPy arrays have different behaviors depending on whether they are mutable or immutable.

### 1. Mutable Arrays

In [31]:
import numpy as np
list_data = [1, 2, 3, 4, 5]
mutable_arr = np.array(list_data)
# Modifying the array
mutable_arr[0] = 10
print("Modified Array:", mutable_arr)

Modified Array: [10  2  3  4  5]


### 2. Immutable Arrays


In [32]:
import numpy as np
tuple_data = (1, 2, 3, 4, 5)
immutable_arr = np.array(tuple_data)
# Attempting to modify the array will raise an error
try:
    immutable_arr[0] = 10
except ValueError as e:
    print("Error:", e) #output is an error

# Split

In NumPy, the split function is used to split an array into multiple sub-arrays along a specified axis. This function is particularly useful when you need to divide a large array into smaller arrays based on specific criteria.

* array: The array to be split.

* indices_or_sections: If an integer n, it specifies the number of equal-sized sub-arrays to create. If a 1-D array of sorted integers, it indicates the indices at which to split the array.

* axis: The axis along which to split the array. Default is 0 (along rows).

### 1. Equal Splitting

In [33]:
import numpy as np
arr = np.arange(12).reshape(4, 3)
print("Original Array:")
print(arr)
# Split into 2 equal parts along rows
split_arr = np.split(arr, 2)
print("\nSplit Arrays:")
for a in split_arr:
    print(a)

Original Array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Split Arrays:
[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


### 2. Splitting with Indices

In [34]:
import numpy as np
arr = np.arange(10)
print("Original Array:", arr)
# Split at indices 3 and 7
split_arr = np.split(arr, [3, 7])
print("\nSplit Arrays:")
for a in split_arr:
    print(a)

Original Array: [0 1 2 3 4 5 6 7 8 9]

Split Arrays:
[0 1 2]
[3 4 5 6]
[7 8 9]


### 3. Splitting Along Columns

In [35]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])
print("Original Array:")
print(arr)
# Split along columns
split_arr = np.split(arr, [2], axis=1)
print("\nSplit Arrays:")
for a in split_arr:
    print(a)

Original Array:
[[1 2 3 4]
 [5 6 7 8]]

Split Arrays:
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]


# Stack

In NumPy, stacking refers to combining arrays along a new axis. This operation is useful when you need to concatenate arrays either vertically (along rows) or horizontally (along columns), depending on the axis specified.



### 1. np.stack


In [36]:
import numpy as n
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked_arr = np.stack((arr1, arr2))
print("Stacked Array:")
print(stacked_arr)

Stacked Array:
[[1 2 3]
 [4 5 6]]


### 2. np.vstack

In [37]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# Stack vertically
stacked_arr = np.vstack((arr1, arr2))
print("Vertically Stacked Array:")
print(stacked_arr)

Vertically Stacked Array:
[[1 2 3]
 [4 5 6]]


### 3. np.hstack

In [38]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# Stack horizontally
stacked_arr = np.hstack((arr1, arr2))
print("Horizontally Stacked Array:")
print(stacked_arr)

Horizontally Stacked Array:
[1 2 3 4 5 6]


### 4. np.dstack


In [39]:
import numpy as np
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])
# Stack depth-wise
stacked_arr = np.dstack((arr1, arr2))
print("Depth-wise Stacked Array:")
print(stacked_arr)

Depth-wise Stacked Array:
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
