# 04/Sep/2023.  

# NUMPY

In [1]:
import numpy as np

# Creation of Array (1d)

In [2]:
mylist1 = [11,22,33,44,55]
n1 = np.array(mylist1)
print(type(n1))

print(n1)

print(n1.ndim)  ##  number of dimensions
print(n1.shape) ##  shape of the array.  count along each available axis

print(n1.size)  ##  total number of elements in the array

print(n1.itemsize) ##  size in bytes of each item in memory
print(n1.dtype)    ##  dtype is the datatype

<class 'numpy.ndarray'>
[11 22 33 44 55]
1
(5,)
5
4
int32


In [3]:
mylist1 = [11,22,33,44,55]
n1 = np.array(mylist1, dtype=np.int8)  ##  range of int8.  -128 to +127
print(n1)
print(n1.itemsize) ##  size in bytes of each item in memory
print(n1.dtype)    ##  dtype is the datatype

[11 22 33 44 55]
1
int8


In [4]:
mylist1 = [11,22,33,44,55.98]
n1 = np.array(mylist1)
print(type(n1))

print(n1)

print(n1.ndim)  ##  number of dimensions
print(n1.shape) ##  shape of the array.  count along each available axis

print(n1.size)  ##  total number of elements in the array

print(n1.itemsize) ##  size in bytes of each item in memory
print(n1.dtype)    ##  dtype is the datatype

<class 'numpy.ndarray'>
[11.   22.   33.   44.   55.98]
1
(5,)
5
8
float64


In [5]:
n1 = np.arange(10,40,2)
print(n1)
print(type(n1))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
<class 'numpy.ndarray'>


In [6]:
n1 = np.arange(10.1,40.9,0.99)
print(n1)
print(type(n1))

[10.1  11.09 12.08 13.07 14.06 15.05 16.04 17.03 18.02 19.01 20.   20.99
 21.98 22.97 23.96 24.95 25.94 26.93 27.92 28.91 29.9  30.89 31.88 32.87
 33.86 34.85 35.84 36.83 37.82 38.81 39.8  40.79]
<class 'numpy.ndarray'>


In [7]:
n1 = np.random.randint(low=10, high=100, size=5)
print(type(n1))
print(n1)
np.random.randint(10,100,size=5)

<class 'numpy.ndarray'>
[97 58 47 44 11]


array([83, 64, 20, 27, 30])

In [14]:
np.random.seed(10)
n1 = np.random.randint(low=10, high=100, size=5)
print(type(n1))
print(n1)

<class 'numpy.ndarray'>
[19 25 74 38 99]


# Creation of 2D Array

In [15]:
mylist2d = [
    [5,3,4],
    [9,0,0]
]

n23 = np.array(mylist2d)

print(n23)

print(n23.ndim)  ##  number of dimensions
print(n23.shape) ##  shape of the array.  count along each available axis

print(n23.size)  ##  total number of elements in the array

[[5 3 4]
 [9 0 0]]
2
(2, 3)
6


In [16]:
n34 = np.arange(12).reshape(3,4)
print(n34)
print(n34.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [23]:
n34 = np.arange(12346580).reshape(-1, 10)
print(n34.shape)
n = np.arange(10)
np.sort(n)

(1234658, 10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
n34 = np.arange(12).reshape(3,4)
print(n34)
print(n34.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [13]:
n34 = np.arange(12).reshape(2,-1)
print(n34)
print(n34.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)


In [14]:
np.random.seed(23)

n46 = np.random.randint(low=10, high=100, size=(4,6))
print(n46.shape)
n46

(4, 6)


array([[93, 50, 83, 64, 41, 86],
       [49, 35, 61, 16, 55, 22],
       [59, 76, 85, 95, 79, 74],
       [22, 31, 58, 51, 89, 72]])

# Extraction of values

In [15]:
np.random.seed(23)

n89 = np.random.randint(low=10, high=100, size=(8,9))
n89

array([[93, 50, 83, 64, 41, 86, 49, 35, 61],
       [16, 55, 22, 59, 76, 85, 95, 79, 74],
       [22, 31, 58, 51, 89, 72, 67, 29, 43],
       [69, 49, 25, 46, 75, 11, 53, 25, 96],
       [93, 68, 35, 76, 84, 45, 66, 23, 70],
       [32, 48, 41, 88, 10, 31, 16, 42, 42],
       [24, 41, 88, 93, 90, 80, 76, 92, 95],
       [65, 37, 72, 53, 84, 81, 52, 93, 31]])

In [16]:
n89[0]

array([93, 50, 83, 64, 41, 86, 49, 35, 61])

In [17]:
n89[0,0]

93

In [18]:
n89[0][0]

93

In [19]:
n89[-1,-1]

31

In [20]:
n89[-1]

array([65, 37, 72, 53, 84, 81, 52, 93, 31])

In [21]:
n89[-1,0]

65

In [22]:
n89[1:4]

array([[16, 55, 22, 59, 76, 85, 95, 79, 74],
       [22, 31, 58, 51, 89, 72, 67, 29, 43],
       [69, 49, 25, 46, 75, 11, 53, 25, 96]])

In [23]:
n89[2:5, 3:7]

array([[51, 89, 72, 67],
       [46, 75, 11, 53],
       [76, 84, 45, 66]])

In [24]:
n89[ [1,3,-2,-1] ]

array([[16, 55, 22, 59, 76, 85, 95, 79, 74],
       [69, 49, 25, 46, 75, 11, 53, 25, 96],
       [24, 41, 88, 93, 90, 80, 76, 92, 95],
       [65, 37, 72, 53, 84, 81, 52, 93, 31]])

In [25]:
n89

array([[93, 50, 83, 64, 41, 86, 49, 35, 61],
       [16, 55, 22, 59, 76, 85, 95, 79, 74],
       [22, 31, 58, 51, 89, 72, 67, 29, 43],
       [69, 49, 25, 46, 75, 11, 53, 25, 96],
       [93, 68, 35, 76, 84, 45, 66, 23, 70],
       [32, 48, 41, 88, 10, 31, 16, 42, 42],
       [24, 41, 88, 93, 90, 80, 76, 92, 95],
       [65, 37, 72, 53, 84, 81, 52, 93, 31]])

In [26]:
n89[ [0,1,-1] , [2,3,4] ]

array([83, 59, 84])

In [27]:
n89[:, 4:6]

array([[41, 86],
       [76, 85],
       [89, 72],
       [75, 11],
       [84, 45],
       [10, 31],
       [90, 80],
       [84, 81]])

In [28]:
n89[:, 4]

array([41, 76, 89, 75, 84, 10, 90, 84])

In [29]:
n89[:, 4:5]

array([[41],
       [76],
       [89],
       [75],
       [84],
       [10],
       [90],
       [84]])

In [30]:
n89[:, [4]]

array([[41],
       [76],
       [89],
       [75],
       [84],
       [10],
       [90],
       [84]])

In [31]:
n89[:, [2,4,-1]]

array([[83, 41, 61],
       [22, 76, 74],
       [58, 89, 43],
       [25, 75, 96],
       [35, 84, 70],
       [41, 10, 42],
       [88, 90, 95],
       [72, 84, 31]])

In [32]:
n89[ [1,3,-1] ]

array([[16, 55, 22, 59, 76, 85, 95, 79, 74],
       [69, 49, 25, 46, 75, 11, 53, 25, 96],
       [65, 37, 72, 53, 84, 81, 52, 93, 31]])

In [33]:
n89[ [1,3,-1] , 5:]

array([[85, 95, 79, 74],
       [11, 53, 25, 96],
       [81, 52, 93, 31]])

In [34]:
n89

array([[93, 50, 83, 64, 41, 86, 49, 35, 61],
       [16, 55, 22, 59, 76, 85, 95, 79, 74],
       [22, 31, 58, 51, 89, 72, 67, 29, 43],
       [69, 49, 25, 46, 75, 11, 53, 25, 96],
       [93, 68, 35, 76, 84, 45, 66, 23, 70],
       [32, 48, 41, 88, 10, 31, 16, 42, 42],
       [24, 41, 88, 93, 90, 80, 76, 92, 95],
       [65, 37, 72, 53, 84, 81, 52, 93, 31]])

In [35]:
mask1 = n89 > 50
mask1

array([[ True, False,  True,  True, False,  True, False, False,  True],
       [False,  True, False,  True,  True,  True,  True,  True,  True],
       [False, False,  True,  True,  True,  True,  True, False, False],
       [ True, False, False, False,  True, False,  True, False,  True],
       [ True,  True, False,  True,  True, False,  True, False,  True],
       [False, False, False,  True, False, False, False, False, False],
       [False, False,  True,  True,  True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True,  True,  True,  True, False]])

In [36]:
mask1.shape

(8, 9)

In [37]:
mask1.dtype

dtype('bool')

In [38]:
n89[mask1]

array([93, 83, 64, 86, 61, 55, 59, 76, 85, 95, 79, 74, 58, 51, 89, 72, 67,
       69, 75, 53, 96, 93, 68, 76, 84, 66, 70, 88, 88, 93, 90, 80, 76, 92,
       95, 65, 72, 53, 84, 81, 52, 93])

In [39]:
n89[n89>50]

array([93, 83, 64, 86, 61, 55, 59, 76, 85, 95, 79, 74, 58, 51, 89, 72, 67,
       69, 75, 53, 96, 93, 68, 76, 84, 66, 70, 88, 88, 93, 90, 80, 76, 92,
       95, 65, 72, 53, 84, 81, 52, 93])

In [40]:
n89

array([[93, 50, 83, 64, 41, 86, 49, 35, 61],
       [16, 55, 22, 59, 76, 85, 95, 79, 74],
       [22, 31, 58, 51, 89, 72, 67, 29, 43],
       [69, 49, 25, 46, 75, 11, 53, 25, 96],
       [93, 68, 35, 76, 84, 45, 66, 23, 70],
       [32, 48, 41, 88, 10, 31, 16, 42, 42],
       [24, 41, 88, 93, 90, 80, 76, 92, 95],
       [65, 37, 72, 53, 84, 81, 52, 93, 31]])

In [41]:
mask1 = n89>50
mask1

array([[ True, False,  True,  True, False,  True, False, False,  True],
       [False,  True, False,  True,  True,  True,  True,  True,  True],
       [False, False,  True,  True,  True,  True,  True, False, False],
       [ True, False, False, False,  True, False,  True, False,  True],
       [ True,  True, False,  True,  True, False,  True, False,  True],
       [False, False, False,  True, False, False, False, False, False],
       [False, False,  True,  True,  True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True,  True,  True,  True, False]])

In [42]:
mask2 = n89%2 ==0
mask2

array([[False,  True, False,  True, False,  True, False, False, False],
       [ True, False,  True, False,  True, False, False, False,  True],
       [ True, False,  True, False, False,  True, False, False, False],
       [False, False, False,  True, False, False, False, False,  True],
       [False,  True, False,  True,  True, False,  True, False,  True],
       [ True,  True, False,  True,  True, False,  True,  True,  True],
       [ True, False,  True, False,  True,  True,  True,  True, False],
       [False, False,  True, False,  True, False,  True, False, False]])

In [43]:
mask3 = mask1 & mask2
mask3

array([[False, False, False,  True, False,  True, False, False, False],
       [False, False, False, False,  True, False, False, False,  True],
       [False, False,  True, False, False,  True, False, False, False],
       [False, False, False, False, False, False, False, False,  True],
       [False,  True, False,  True,  True, False,  True, False,  True],
       [False, False, False,  True, False, False, False, False, False],
       [False, False,  True, False,  True,  True,  True,  True, False],
       [False, False,  True, False,  True, False,  True, False, False]])

In [ ]:
n89[mask3]

In [ ]:
n89[  (n89>50) & (n89%2==0)]

# Mutability

In [ ]:
n89

In [ ]:
n89[0,0] = 999

In [ ]:
n89

In [ ]:
n89[n89>50] = 888

In [ ]:
n89

In [ ]:
n89[2:5] = 777

In [ ]:
n89

In [ ]:
n89[2:5, 2:5] = 666

In [ ]:
n89

# Splitting of Arrays

In [ ]:
np.random.seed(23)
n812 = np.random.randint(low=10, high=100, size=(8,12))
n812

In [ ]:
r = np.vsplit(n812, 2)
print(type(r))

for item in r:
    print(item)
    print()

In [ ]:
r = np.vsplit(n812, 4)
print(type(r))

for item in r:
    print(item)
    print()

In [ ]:
r = np.vsplit(n812, 3)

In [ ]:
np.vsplit(n812, [3,4,6,7]   )

In [ ]:
np.vsplit(n812, [2,3,4,6]   )

In [ ]:
np.hsplit(n812, 2  ) 

In [ ]:
r = np.hsplit(n812, [3,4,6,8,9,11]   )  ##  returns a list of numpy arrays
for item in r:
    print(item)
    print(item.shape)
    print(type(item))
    print()

In [ ]:
##  DIY: np.dsplit

# hStack, vStack

In [ ]:
n34 = np.arange(12).reshape(3,4)
n64 = np.arange(100,124).reshape(6,4)
n36 = np.arange(200,218).reshape(3,6)

In [ ]:
np.vstack(tup=(n34,n64))

In [ ]:
np.hstack(tup=(n34,n64))

In [ ]:
np.hstack(tup=(n34,n36))

In [ ]:
#DIY: dstack

3d matrix

In [ ]:
ulist = [10,20,30]
ulist1 = [
    10,
    20,30
]

In [ ]:
mylist432 = [
    [ 
        [111,121], 
        [141,151], 
        [171,181] 
    ],
    [ [211,221], [241,251], [271,281] ],    [ [311,321], [341,351], [371,381] ],    [ [411,421], [441,451], [471,481] ],
]

In [ ]:
n432 = np.array(mylist432)
n432.shape

In [ ]:
n432

In [ ]:
n432[1,1,1]

In [ ]:
n432[2,1,0]

In [ ]:
n432[1:3, 1:, 1]

# Looping

In [ ]:
n34 = np.arange(100,112).reshape(3,4)
n34

In [ ]:
for row in n34:
    print(row)
    print()

In [ ]:
print(n34)
for item in np.nditer(n34, order='C'):
    print(item)
    print()

In [ ]:
print(n34)
for item in np.nditer(n34, order='F'):
    print(item)
    print()

In [ ]:
print(n34)

for item in np.ndenumerate(n34):
    print(item)

In [ ]:
print(n34)

for index, value in np.ndenumerate(n34):
    print(index, value)

# Operations on Arrays

In [ ]:
# +, *, @ , transpose, 

In [ ]:
highprice = np.random.randint(low=10, high=100, size=10)
lowprice = np.random.randint(low=10, high=100, size=10)
print(highprice)
print(lowprice)

volatility = highprice - lowprice
print(volatility)

In [ ]:
n34a = np.random.randint(low=10, high=100, size=(3,4))
n34b = np.random.randint(low=10, high=100, size=(3,4))
print(n34a)
print(n34b)

n34c = n34a + n34b
print(n34c)

In [ ]:
n34a * n34c

In [ ]:
##  MxN  @ NxK  -->  MxK   sum of products

In [ ]:
n34a@n34b  ##  error

In [ ]:
n43 = n34b.T  ##  transpose
n43

In [ ]:
n34a@n43  ##  matmul

# Other Utility Functions

In [ ]:
#identity, ones, zeros, full

In [ ]:
np.zeros(shape=(3,4))

In [ ]:
np.zeros(shape=(3,4), dtype=np.int32)

In [ ]:
np.ones(shape=(3,4))

In [ ]:
np.full(shape=(3,4), fill_value=55)

In [17]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# sum, min, max,mean

In [ ]:
np.random.seed(23)
n34 = np.random.randint(low=1, high=9, size=(3,4))
n34

In [ ]:
print(n34)
print(np.sum(n34, axis=None))
print(np.sum(n34, axis=0))
print(np.sum(n34, axis=1))

In [ ]:
print(n34)
print(np.min(n34, axis=None))
print(np.min(n34, axis=0))
print(np.min(n34, axis=1))

In [ ]:
print(n34)
print(np.max(n34, axis=None))
print(np.max(n34, axis=0))
print(np.max(n34, axis=1))

In [ ]:
print(n34)
print(np.mean(n34, axis=None))
print(np.mean(n34, axis=0))
print(np.mean(n34, axis=1))

In [ ]:
# power, remainder

In [ ]:
print(n34)
np.power(n34,3)

In [ ]:
print(n34)
np.power(n34,n34)

In [ ]:
print(n34)
np.remainder(n34,2)

In [ ]:
#linspace

In [18]:
np.linspace(start=0, stop=7,num=8, retstep=True)

(array([0., 1., 2., 3., 4., 5., 6., 7.]), 1.0)

In [19]:
np.linspace(start=-1, stop=1,num=5, retstep=True)

(array([-1. , -0.5,  0. ,  0.5,  1. ]), 0.5)

In [ ]:
np.linspace(start=3, stop=5,num=9, retstep=True)

In [ ]:
# rand and randn

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
n1 = np.random.rand(40,40) ## generates values within uniform dist framework
print(n1.shape)
print(n1.min())
print(n1.max())
print(n1.mean())
plt.scatter(n1,n1.T)
plt.show()

In [ ]:
n1 = np.random.randn(40,40) ## generates values within normal dist framework
print(n1.shape)
print(n1.min())
print(n1.max())
print(n1.mean())
plt.hist(n1)
plt.show()

# Intersect

In [ ]:
n1 = np.random.randint(low=10,high=25, size=20)
n2 = np.random.randint(low=10,high=25, size=20)
print(n1)
print(n2)

In [ ]:
np.intersect1d(n1,n2)

In [ ]:
np.union1d(n1,n2)

In [ ]:
n34

In [ ]:
n34**4