### Join

In [5]:

import numpy as np
from numpy import random

In [6]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

In [7]:
res=np.concatenate((arr1,arr2),axis=0)

In [8]:
res

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

###  Stack

In [10]:
res=np.stack((arr1,arr2),axis=1)
res

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [11]:
res=np.hstack((arr1,arr2))
res

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
res=np.vstack((arr1,arr2))
res

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
res=np.dstack((arr1,arr2))

In [14]:
res

array([[[ 1,  6],
        [ 2,  7],
        [ 3,  8],
        [ 4,  9],
        [ 5, 10]]])

### Split 

In [16]:
arr1=np.array([1,2,3,4,5,6])

new_arr=np.split(arr1,2)
new_arr

[array([1, 2, 3]), array([4, 5, 6])]

In [17]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [18]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
new_arr=np.array_split(arr2,3)
new_arr

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]

# Random Module

In [21]:
arr=random.randint(10,size=2)
arr

array([2, 2])

In [22]:
#using reshape

In [41]:
arr=random.randint(low=10,high=100,size=100).reshape(10,10)
arr

array([[65, 55, 59, 20, 43, 56, 81, 46, 91, 14],
       [97, 37, 80, 11, 84, 50, 11, 88, 46, 74],
       [84, 77, 69, 64, 22, 65, 55, 81, 80, 74],
       [43, 75, 94, 74, 73, 54, 52, 46, 81, 24],
       [72, 16, 89, 67, 88, 54, 13, 75, 10, 94],
       [51, 49, 12, 92, 75, 79, 57, 44, 31, 79],
       [10, 58, 39, 51, 34, 69, 37, 95, 93, 40],
       [36, 77, 65, 34, 37, 19, 98, 66, 67, 31],
       [25, 14, 30, 92, 11, 38, 99, 36, 48, 48],
       [99, 51, 21, 14, 23, 86, 76, 30, 27, 53]])

In [43]:
filters_data=arr>30
res=arr[filters_data]
res


array([65, 55, 59, 43, 56, 81, 46, 91, 97, 37, 80, 84, 50, 88, 46, 74, 84,
       77, 69, 64, 65, 55, 81, 80, 74, 43, 75, 94, 74, 73, 54, 52, 46, 81,
       72, 89, 67, 88, 54, 75, 94, 51, 49, 92, 75, 79, 57, 44, 31, 79, 58,
       39, 51, 34, 69, 37, 95, 93, 40, 36, 77, 65, 34, 37, 98, 66, 67, 31,
       92, 38, 99, 36, 48, 48, 99, 51, 86, 76, 53])