# Looping

In [2]:
import numpy as np

In [6]:
arr=np.array([1,2,3,4,5])

for i in arr:
    print(i)

1
2
3
4
5


In [8]:
arr1=np.array([[1,2,4],[5,6,7]])

for i in arr1:
    print(i)

[1 2 4]
[5 6 7]


In [10]:
for i in arr1:
    for j in i:
        print(j)

1
2
4
5
6
7


In [12]:
for i in np.nditer(arr1):
    print(i)

1
2
4
5
6
7


In [16]:
arr2=np.array([[[1,2,4],[5,6,7]],[[1,2,3],[9,8,7]]])

for i in arr2:
    print(i)

[[1 2 4]
 [5 6 7]]
[[1 2 3]
 [9 8 7]]


In [18]:
for i in arr2:
    for j in i:
        for k in j:
            print(k)

1
2
4
5
6
7
1
2
3
9
8
7


In [20]:
for i in np.nditer(arr2):
    print(i)

1
2
4
5
6
7
1
2
3
9
8
7


In [22]:
#data types

In [24]:
arr=np.array([1,2,34,8])

arr.dtype

dtype('int32')

In [29]:
#different data types

In [33]:
for i in np.nditer(arr,flags=["buffered"],op_dtypes=["S"]):
    print(i)

b'1'
b'2'
b'34'
b'8'


In [35]:
#enumerator - coordinator 

In [39]:
for i in np.ndenumerate(arr):
    print(i)

((0,), 1)
((1,), 2)
((2,), 34)
((3,), 8)


In [41]:
for i ,j in np.ndenumerate(arr):
    print(i,j)

(0,) 1
(1,) 2
(2,) 34
(3,) 8


# Sorting 

In [72]:
arr=np.array([37,9,3,1,2,1,7,8,9,21,-1,0])
sorted1=np.sort(arr)


In [74]:
sorted1

array([-1,  0,  1,  1,  2,  3,  7,  8,  9,  9, 21, 37])

In [76]:
sorted

array(['A', 'B', 'C', 'D', 'E'], dtype='<U1')

In [78]:
arr

array([37,  9,  3,  1,  2,  1,  7,  8,  9, 21, -1,  0])

In [54]:
# arg sort

arr1=np.array([1,3,2,4,5])
indices=np.argsort(arr1)

arr2=np.array(["A","C","B","D","E"])
sorted=arr2[indices]
sorted

array(['A', 'B', 'C', 'D', 'E'], dtype='<U1')

In [58]:
#inplace

In [80]:
arr=np.array([37,9,3,1,2,1,7,8,9,21,-1,0])

In [82]:
arr.sort()

In [84]:
arr

array([-1,  0,  1,  1,  2,  3,  7,  8,  9,  9, 21, 37])

# Data types

In [98]:
arr=np.array([1,22,2,22])
print(arr.dtype)

int32


In [ ]:
#creat with different datatype

In [104]:
arr1=np.array([1,2,4,5],dtype="S")
print(arr1.dtype)

|S1


In [110]:
#convert one data type to another type

In [112]:
arr2=np.array([2.3,4.6,7.8])
new_arr=arr2.astype(int)
new_arr

array([2, 4, 7])

In [114]:
new_arr.dtype

dtype('int32')