# Mathematical functions

In [12]:
import numpy as np

In [14]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([3,4,5,6,7,8])

In [16]:
res=np.add(arr1,arr2)

In [18]:
res

array([ 4,  6,  8, 10, 12, 14])

In [20]:
#sum


In [22]:
total_sum=np.sum(arr1)

In [24]:
total_sum

21

In [26]:
mean_value=np.mean(arr1)

In [28]:
mean_value

3.5

In [30]:
max_value=np.max(arr1)

In [32]:
max_value

6

# Statistical functions

In [47]:
arr1=np.array([1,3,4,2,5])
arr1.sort()

In [49]:
arr1

array([1, 2, 3, 4, 5])

In [51]:
median_value=np.median(arr1)
median_value

3.0

In [54]:
std_value=np.std(arr1)

In [56]:
std_value

1.4142135623730951

In [58]:
var_value=np.var(arr1)
var_value

2.0

In [60]:
min_value=np.min(arr1)
min_value

1

In [62]:
#range

range_value=np.ptp(arr1)
range_value

4

In [64]:
#percentile

In [66]:
percentile_50th=np.percentile(arr1,50)
percentile_50th

3.0

In [68]:
product=np.prod(arr1)
product

120

In [70]:
cum_sum=np.cumsum(arr1)

In [72]:
cum_sum

array([ 1,  3,  6, 10, 15])

In [74]:
cum_product=np.cumprod(arr1)
cum_product

array([  1,   2,   6,  24, 120])

In [76]:
#unique elements


In [80]:
element,count =np.unique(arr1,return_counts=True)
element

array([1, 2, 3, 4, 5])

In [84]:
count

array([1, 1, 1, 1, 1], dtype=int64)

In [92]:
#boolean operations

In [88]:
bool_arr=arr1>1
bool_arr

array([False,  True,  True,  True,  True])

In [90]:
bool_arr=arr1>1
filtered_data=arr1[bool_arr]
filtered_data

array([2, 3, 4, 5])