# Numpy Methods 

In [22]:
import numpy as np

###  Copy

In [24]:
arr=np.array([1,2,3,4,5,6,9])

new_arr=arr.copy()

In [25]:
new_arr

array([1, 2, 3, 4, 5, 6, 9])

In [26]:
new_arr[0]=12
new_arr

array([12,  2,  3,  4,  5,  6,  9])

In [27]:
arr

array([1, 2, 3, 4, 5, 6, 9])

### View

In [29]:
arr1=np.array([1,2,3,5])

In [30]:
new_view=arr1.view()
new_view[0]=22
new_view


array([22,  2,  3,  5])

In [31]:
arr1

array([22,  2,  3,  5])

### Shape 

In [33]:
arr3=np.array([[1,2,3,4],[5,6,7,8]])
arr3.shape

(2, 4)

In [34]:
# to create a ndim array

In [35]:
# arr4=np.array([1,2,3,4],ndim=5)
# arr4


###  Reshape

In [37]:
arr4 = np.array([1, 2, 3, 4]).reshape(2,2)
print(arr4)

[[1 2]
 [3 4]]


### Arange 

In [39]:
arr5=np.arange(1,10)
arr5

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr7=np.arange(1,50,5)
arr7

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [41]:
arr7.size

10

In [42]:
arr7.itemsize

4

### linespace

In [44]:
arr=np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Concatenate 

In [46]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

res=np.concatenate((arr1,arr2))
res

array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
arr1=np.array([[1,2,3,4],[3,4,5,6]])
arr2=np.array([[5,6,7,8],[1,2,3,4]])

res=np.concatenate((arr1,arr2),axis=0)
res

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [48]:
#axis - 0 column , axis - 1 row

### Arithmetic operations 

In [50]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

arr1+arr2
arr1-arr2
arr1*arr2
arr1/arr2

arr1+10

array([11, 12, 13, 14])