# Numpy

In [9]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [11]:
import numpy as np

In [13]:
#zero dimensional

In [15]:
zero_dim=np.array(4)

In [17]:
zero_dim

array(4)

In [19]:
zero_dim.ndim

0

In [21]:
#one dimesional

In [106]:
one_dim=np.array([1,2,3,45,40])
print("dim",one_dim.ndim)
print("index",one_dim[2])

#slicing
print(one_dim[1:4])

#negative slicing
print(one_dim[-3:])

dim 1
index 3
[ 2  3 45]
[ 3 45 40]


In [25]:
#two dimensional

In [116]:
two_dim=np.array([[1,2,4],[5,6,7]])
print("dim",two_dim.ndim)
print("index",two_dim[0,1])
print("index",two_dim[1,0])

# negative indexing 
print("index",two_dim[1,-2])

#slicing
print(two_dim[0,1:])

dim 2
index 2
index 5
index 6
[2 4]


In [31]:
#three dimensional array

In [118]:
three_dim=np.array([[[1,2,3],[4,5,6]],[[2,3,4],[5,6,7]]])
print("dim",three_dim.ndim)
print("index",three_dim[0,0,0])
print("index",three_dim[0,1,0])
print("index",three_dim[1,0,0])
print("index",three_dim[1,1,0])

#slicing
print(three_dim[0,0,1:])

dim 3
index 1
index 4
index 2
index 5
[2 3]


In [37]:
#function creation

In [46]:
#identity

In [48]:
identity_arr=np.identity(3)
identity_arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
#zeros

In [58]:
zero_arr=np.zeros((3,3))
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [60]:
#ones

In [64]:
one_arr=np.ones((3,4))
one_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [66]:
#full


In [72]:
full_arr=np.full((3,3),4)
full_arr

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])