# Array Creation


In [2]:
import numpy as np

In [3]:
df=np.array(7)

In [4]:
print("No of dim:",df.ndim)

No of dim: 0


In [ ]:
arr=np.array([1,2,3,45,5])
arr.ndim

1

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.dtype

dtype('int32')

In [ ]:
arr[3]

45

In [ ]:
#2 d array

In [ ]:
arr=np.array([[1,2,3],[4,6,7]])

In [ ]:
arr.ndim

2

In [ ]:
arr[0,1]

2

In [ ]:
arr[1,0]

4

In [ ]:
#3 d array

In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[4,5,6],[9,2,1]]])

In [ ]:
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[4, 5, 6],
        [9, 2, 1]]])

In [ ]:
arr.ndim

3

In [ ]:
arr[0,0,0]

1

In [ ]:
arr[0,1,0]

4

In [ ]:
arr[1,0,0]

4

In [ ]:
arr[1,1,0]

9

In [ ]:
arr=np.array([1,2,4,5],ndmin=5)

In [ ]:
arr.ndim

5

In [ ]:
arr

array([[[[[1, 2, 4, 5]]]]])

### Creating a array using Functions

In [ ]:
#identity

In [ ]:
matrix=np.identity(3)

In [ ]:
matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#ones

In [ ]:
matrix=np.ones((3,4))
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#zeros

In [ ]:
matrix=np.zeros((2,3))

In [ ]:
matrix

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
matrix=np.full((3,3),5)

In [ ]:
matrix

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
#slicing

In [ ]:
arr=np.array([[1,2,3],[4,6,7]])

In [ ]:
arr[0,:2]

array([1, 2])

In [ ]:
arr[1,1:]

array([6, 7])

In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[4,5,6],[9,2,1]]])

In [ ]:
arr[0,0,1:]

array([2, 3])

### Loop

In [ ]:
arr=np.array([1,2,4,5,6,7])

In [ ]:
for i in arr:
    print(i)

1
2
4
5
6
7


In [ ]:
# 2d array

In [ ]:
arr=np.array([[1,2,3],[4,6,7]])

In [ ]:
for i in arr:
    for j in i:
        print(j)

1
2
3
4
6
7


In [ ]:
# 3 d array

In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[4,5,6],[9,2,1]]])

In [ ]:
for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
4
5
6
9
2
1


In [ ]:
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
4
5
6
9
2
1
