# Numpy Intro

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [18]:
#zero dimension array

In [22]:
arr=np.array(21)
arr

array(21)

In [16]:
#one Dimensional Array

In [44]:
arr=np.array([1,2,3,4,5])

In [46]:
arr.ndim

1

In [9]:
arr

array([1, 2, 3, 4, 5])

In [24]:
#two dimensional array

In [28]:
arr=np.array([[1,2,3],[4,5,6]])

In [30]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr = np.array([[[1,2,3],[4,5,6]],[[4,5,6],[7,8,9]]])

In [38]:
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[4, 5, 6],
        [7, 8, 9]]])

In [40]:
arr.ndim

3