In [76]:
import numpy as np
from numpy import random

### Mathematical Functions

In [79]:
arr1=np.array([1,2,3,4,5,6,7])
arr2=np.array([6,2,3,4,5])

# res=np.add(arr1,arr2)
# res


In [81]:
sum_arr=np.sum(arr1)
sum_arr

28

### Statistical functions 

In [84]:
mean_value=np.mean(arr1)
mean_value

4.0

In [86]:
median_value=np.median(arr1)
median_value

4.0

In [88]:
std_value=np.std(arr1)
std_value

2.0

In [90]:
var_value=np.var(arr1)
var_value

4.0

In [92]:
min_value=np.min(arr1)
min_value

1

In [94]:
max_value=np.max(arr1)
max_value

7

In [96]:
percentile_50=np.percentile(arr1,75)
percentile_50


5.5

In [98]:
product=np.prod(arr1)
product

5040

In [100]:
cum_product=np.cumprod(arr1)

In [102]:
cum_product

array([   1,    2,    6,   24,  120,  720, 5040])

In [104]:
cum_sum=np.cumsum(arr1)
cum_sum

array([ 1,  3,  6, 10, 15, 21, 28])

In [106]:
count=np.unique(arr1,return_counts=True)
count

(array([1, 2, 3, 4, 5, 6, 7]), array([1, 1, 1, 1, 1, 1, 1], dtype=int64))

### Boolean Operations 

In [109]:
bool_condition=arr1>5

In [111]:
bool_condition

array([False, False, False, False, False,  True,  True])

In [113]:
res=arr1[bool_condition]

In [115]:
res

array([6, 7])

### Random Module 

In [126]:
arr=random.randint(20,size=(6))
arr

array([11, 17,  8,  2,  3, 18])

In [140]:
data=random.randint(low=10,high=100,size=(100)).reshape(10,10)

In [142]:
data

array([[58, 14, 20, 96, 71, 57, 54, 47, 97, 98],
       [22, 63, 45, 91, 83, 66, 20, 67, 13, 97],
       [72, 80, 27, 32, 84, 47, 42, 35, 10, 49],
       [63, 38, 80, 76, 57, 47, 42, 53, 87, 44],
       [96, 33, 98, 98, 40, 84, 78, 17, 44, 85],
       [75, 13, 87, 83, 33, 42, 64, 20, 94, 13],
       [61, 94, 20, 72, 72, 11, 15, 53, 31, 64],
       [70, 48, 71, 20, 39, 21, 89, 34, 14, 83],
       [11, 92, 93, 98, 19, 97, 46, 17, 14, 68],
       [44, 57, 55, 94, 19, 30, 79, 10, 20, 37]])

### split stack

In [192]:

data = np.array([[1, 2, 3], [6, 7, 8]])
res = np.array_split(data, 3, axis=1)
print(res)


[array([[1],
       [6]]), array([[2],
       [7]]), array([[3],
       [8]])]


In [204]:
arr1=np.array([1,4,6])
arr2=np.array([1,3,5])

res=np.stack((arr1,arr2),axis=0)
res

array([[1, 4, 6],
       [1, 3, 5]])

In [210]:
res=np.vstack((arr1,arr2))
res

array([[1, 4, 6],
       [1, 3, 5]])

In [212]:
res=np.hstack((arr1,arr2))
res

array([1, 4, 6, 1, 3, 5])