# Numpy Methods 

###  sort

In [3]:
import numpy as np

In [5]:
arr=np.array([1,2,3,10,-1,3,90])

In [7]:
sorted_arr=np.sort(arr)
sorted_arr

array([-1,  1,  2,  3,  3, 10, 90])

In [9]:
#argsort

In [13]:
arr=np.array([1,2,4,3,5])

indices=np.argsort(arr)

In [17]:
arr2=np.array(["A","B","D","C","E"])

In [19]:
sorted_arr=arr2[indices]

In [21]:
sorted_arr

array(['A', 'B', 'C', 'D', 'E'], dtype='<U1')

In [23]:
#multidimensional array

In [31]:
arr=np.array([[7,3,2],[5,4,6]])

In [37]:
sorted_arr=np.sort(arr,axis=0) #axis=0 row wise

In [39]:
sorted_arr

array([[5, 3, 2],
       [7, 4, 6]])

In [43]:
sorted_arr=np.sort(arr,axis=1) #axis=1 column wise sorting
sorted_arr

array([[2, 3, 7],
       [4, 5, 6]])

In [46]:
arr

array([[7, 3, 2],
       [5, 4, 6]])

In [48]:
#inplacesort

In [50]:
arr.sort()

In [52]:
arr

array([[2, 3, 7],
       [4, 5, 6]])

### Copy vs view 

In [55]:
arr=np.array([1,2,3,4,5])

arr2=np.copy(arr)

In [57]:
arr

array([1, 2, 3, 4, 5])

In [59]:
arr2

array([1, 2, 3, 4, 5])

In [61]:
arr[0]=10

In [63]:
arr

array([10,  2,  3,  4,  5])

In [65]:
arr2

array([1, 2, 3, 4, 5])

In [67]:
#view

In [69]:
arr=np.array([1,2,3,4,5])


In [75]:
arr2=arr.view()

In [77]:
arr

array([1, 2, 3, 4, 5])

In [79]:
arr2

array([1, 2, 3, 4, 5])

In [81]:
arr[0]=12


In [83]:
arr

array([12,  2,  3,  4,  5])

In [85]:
arr2

array([12,  2,  3,  4,  5])

### arange 

In [88]:
arr=np.arange(12)

In [90]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### linspace

In [105]:
arr=np.linspace(1,20,4)

In [107]:
arr

array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

### shape & reshape

In [129]:
arr=np.array([1,2,3,4,5])

In [131]:
shape=np.shape(arr)

In [133]:
shape

(5,)

In [135]:
arr=np.array([[1,2,3,4],[5,7,6,1]])

In [137]:
shape=np.shape(arr)

In [139]:
shape

(2, 4)

In [141]:
reshaped_arr=arr.reshape(4,2)

In [143]:
reshaped_arr

array([[1, 2],
       [3, 4],
       [5, 7],
       [6, 1]])

### concatnate 

In [174]:
arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[5,6,7,8],[1,2,3,4]])

In [176]:
res=np.concatenate((arr1,arr2))

In [178]:
res

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [180]:
res=np.concatenate((arr1,arr2),axis=1)

In [182]:
res

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 1, 2, 3, 4]])

### Arithmetic operations

In [189]:
arr=np.array([1,2,3,4])
arr1=np.array([5,6,7,8])

In [191]:
arr+arr1

array([ 6,  8, 10, 12])

In [193]:
arr-arr1

array([-4, -4, -4, -4])

In [195]:
arr*arr1

array([ 5, 12, 21, 32])

In [197]:
arr/arr1

array([0.2       , 0.33333333, 0.42857143, 0.5       ])