# Arithmetic Operations 

In [3]:
import numpy as np

In [5]:
#create two array

In [9]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [11]:
#arithmetic operations

In [13]:
print(a+b)

[5 7 9]


In [15]:
print(a-b)

[-3 -3 -3]


In [17]:
print(a*b)

[ 4 10 18]


In [19]:
print(a/b)

[0.25 0.4  0.5 ]


In [21]:
print(a**b)

[  1  32 729]


In [23]:
#scalar operations

In [25]:
print(a+10)

[11 12 13]


In [27]:
print(a*3)

[3 6 9]


# Matrix Operations 

<p style="color:black font-size:16px">Matrix manipulations like matrix multiplication, transposition, inverse, etc., are commonly used in data manipulation.</p>

### Matrix multiplication 

In [33]:
# use np.dot() or the @ operator.

In [35]:
#create two 2d arrays (matrixex)

In [41]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [43]:
print(np.dot(A,B))

[[19 22]
 [43 50]]


In [45]:
print(A @ B)

[[19 22]
 [43 50]]


### Matrix Transposition

In [48]:
# using .T attributes

In [50]:
print(A.T)

[[1 3]
 [2 4]]


### Identity Matrix 

In [53]:
# using eye()

In [55]:
#create a 3*3 identity matrix

In [57]:
I=np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Inverse of a Matrix 

In [60]:
#using np.linalg.inv()

In [68]:
A=np.array([[1,2],[3,4]])

In [70]:
inv_A=np.linalg.inv(A)

In [72]:
print(inv_A)

[[-2.   1. ]
 [ 1.5 -0.5]]


### Determinant of  a matrix

In [75]:
det_A =np.linalg.det(A)
print(det_A)

-2.0000000000000004


### Broadcasting in Arithmetic Operations 

In [84]:
a=np.array([1,2,3])
b=np.array([[10],[20],[30]])

In [86]:
print(a+b)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
