# Array Sorting

### sort 

In [4]:
import numpy as np

In [5]:
arr=np.array([3,1,2,5,4])

In [6]:
sorted_arr=np.sort(arr)
print(sorted_arr,"sorted arr")

[1 2 3 4 5] sorted arr


### argsort 

In [8]:
# indices that would sort the array. It’s useful when you want to sort based on one array 
#and apply the same sorting order to another array.

In [9]:
arr=np.array([3,1,2,5,4])

In [10]:
indices=np.argsort(arr)

In [11]:
print("Indices that would sort the array:",indices)

Indices that would sort the array: [1 2 0 4 3]


In [12]:
another_arr=np.array(['c','A','B','E','D'])
sorted_another_arr=another_arr[indices]
print("sorted another array:",sorted_another_arr)

sorted another array: ['A' 'B' 'c' 'D' 'E']


### Sorting Multi- Dimensional Arrays 

In [28]:
arr_2d=np.array([[3,6,2],[6,5,4]])

sorted_2d_rows = np.sort(arr_2d,axis=0)
print("Sorted along rows :\n",sorted_2d_rows)

sorted_2d_columns=np.sort(arr_2d,axis=1)
print("Sorted along coloumns:\n",sorted_2d_columns)


Sorted along rows :
 [[3 5 2]
 [6 6 4]]
Sorted along coloumns:
 [[2 3 6]
 [4 5 6]]


### In-Place Sort

In [30]:
arr=np.array([3,1,2,5,4])
arr.sort()
print(arr,"sorted array")

[1 2 3 4 5] sorted array
