# Array Statistical Functions

### Mean

In [3]:
import numpy as np

In [5]:
a=np.array([1,2,3,4,5])

In [7]:
mean_value=np.mean(a)

In [9]:
print(mean_value)

3.0


### Median 

In [12]:
# middle value of the array when it is sorted.

In [14]:
median_value=np.median(a)

In [16]:
print(median_value)

3.0


### Standard Deviation 

In [23]:
# measures the spread of the data relative to the mean

In [25]:
std_value=np.std(a)

In [27]:
print(std_value)

1.4142135623730951


### variance 

In [34]:
#standard deviation and shows how much the data varies from the mean.

In [36]:
variance_value=np.var(a)

In [38]:
print(variance_value)

2.0


### Minimum 

In [41]:
min_value=np.min(a)

In [43]:
print(min_value)

1


### Maximum 

In [46]:
max_value=np.max(a)

In [48]:
print(max_value)

5


### Range (Max -Min) 

In [51]:
range_value=np.ptp(a)

In [53]:
print(range_value)

4


### Percentile 

In [66]:
# value below which a given percentage of observations
 #Calculate 50th percentile (same as median)

In [68]:
percentile_50=np.percentile(a,50)

In [70]:
print(percentile_50)

3.0


### Sum 

In [73]:
sum_value=np.sum(a)

In [75]:
print(sum_value)

15


### Product 

In [78]:
product_value=np.prod(a)

In [80]:
print(product_value)

120


### Cumulative Sum 

In [83]:
cumsum_value=np.cumsum(a)
print(cumsum_value)

[ 1  3  6 10 15]


### cumulative Product 

In [86]:
cumprod_value=np.cumprod(a)
print(cumprod_value)

[  1   2   6  24 120]


### Unique elements and counts 

In [94]:
# Example array
b = np.array([1, 2, 2, 3, 3, 3])


unique_values, counts = np.unique(b, return_counts=True)
print(unique_values)  
print(counts)        


[1 2 3]
[1 2 3]
