# Array Creation Functions

### Identity 

In [3]:
#Purpose: Creates a square identity matrix.
#Shape: The output is a 2D array where the diagonal elements are 1 and all other elements are 0.

In [5]:
import numpy as np

In [ ]:
#identity_matrix = np.identity(n)

In [7]:
identity_matrix=np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Ones 

In [12]:
#Purpose: Creates an array filled with 1s.
#Shape: The shape of the output is determined by the given argument.

In [16]:
#ones_array = np.ones(shape, dtype=None)
#shape: Tuple defining the shape of the array.
#dtype: Optional, specifies the data type (e.g., int, float).

In [20]:
ones_array=np.ones((2,3))
print(ones_array)


[[1. 1. 1.]
 [1. 1. 1.]]


### zeros

In [23]:
#Purpose: Creates an array filled with 0s.
#Shape: Like ones, the shape of the array is defined by the user.

In [29]:
#zeros_array = np.zeros(shape, dtype=None)

In [31]:
zeros_array=np.zeros((3,2))
print(zeros_array)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


### full 

In [34]:
#Purpose: Creates an array filled with a specified constant value.
#Shape: Defined by the input shape, but the entire array is filled with a constant.

In [36]:
#full_array = np.full(shape, fill_value, dtype=None)

In [38]:
full_value=np.full((2,3),7)
print(full_value)

[[7 7 7]
 [7 7 7]]
