# Join Split Stack 

### Join 

In [3]:
import numpy as np

In [5]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])

In [9]:
#rows
result=np.concatenate((a,b),axis=0)
print(result)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
# - vertical stacking - vstack
result=np.vstack((a,b))
print(result)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
#horizontal stacking - hstack
result=np.hstack((a,b.T))
print(result)

[[1 2 5]
 [3 4 6]]


### Split 

In [29]:
#Splitting arrays divides them into sub-arrays.
a=np.array([[1,2,3],[4,5,6]])

result=np.split(a,3,axis=1)
print(result)

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


### Stack 

In [34]:
a=np.array([1,2,3])
b=np.array([4,5,6])

#stack along a new axis
result=np.stack((a,b),axis=0)
print(result)

[[1 2 3]
 [4 5 6]]


In [36]:
result=np.vstack((a,b))
print(result)

[[1 2 3]
 [4 5 6]]
