In [86]:
from numpy import random

In [3]:
#get random number from 0-5

In [27]:
n=random.randint(5)
print("Random Number:",n)

Random Number: 4


In [33]:
# get  3 random numbers as array elements from 0 to 10

In [35]:
n=random.randint(10,size=(3))
print(n)

[0 3 1]


In [83]:
# choice

In [79]:
n=random.choice([10,20,30,40,50,60,70,80,90,100])
print("Random Number:",n)

Random Number: 70


# Random Number Generation with Reshaping

In [108]:
n=random.randint(low=10,high=100,size=100).reshape(10,10)
print(n)

[[45 43 11 57 32 83 94 28 68 90]
 [65 20 63 86 66 75 85 60 81 33]
 [73 29 42 27 13 90 64 77 10 95]
 [81 25 94 18 68 43 57 52 26 84]
 [20 64 42 81 17 80 13 64 27 50]
 [65 90 38 26 45 62 29 25 65 62]
 [56 30 45 44 51 17 15 82 87 62]
 [38 20 21 35 69 70 92 67 46 23]
 [41 47 48 29 82 79 51 39 37 37]
 [15 80 30 99 66 78 52 56 89 48]]


# using Random Seeds 

In [129]:
n=random.seed(23)
print(n)

None


In [131]:
n=random.randint(100)
print(n)

83


In [134]:
n1=random.randint(low=10,high=100,size=5)
print(n1)

[50 83 64 41 86]


# Reshaping Arrays 

In [138]:
n1=random.randint(10,100,20).reshape(4,5)
print(n1)

[[49 35 61 16 55]
 [22 59 76 85 95]
 [79 74 22 31 58]
 [51 89 72 67 29]]


In [145]:
import numpy as np
n2=np.arange(1,11).reshape(2,5)
print(n2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [147]:
#automatic row creation using -1

In [149]:
n3=np.arange(12).reshape(3,-1)
print(n3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [151]:
n4=np.arange(100).reshape(-1,10)
print(n4)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


# Condition Based Selection 

In [154]:
n4[n4>=90]

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# Array Properties 

In [161]:
n5=np.arange(12).reshape(3,4)
print(n5.shape)
print(n5)

(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# Putting It All Together 

In [166]:
import numpy as np

In [168]:
#setting the seed for reproduciblity

In [170]:
n=np.random.seed(23)
print(n)

None


In [172]:
# generate random integers between 10 - 100 reshape into a 4*5

In [174]:
n1=np.random.randint(low=10,high=100,size=(4,6))
print(n1)

[[93 50 83 64 41 86]
 [49 35 61 16 55 22]
 [59 76 85 95 79 74]
 [22 31 58 51 89 72]]


In [176]:
#checking the shape of the array

In [178]:
print("shape of n1:",n1.shape)

shape of n1: (4, 6)


In [180]:
#generating another array with different shape

In [182]:
n5=np.arange(100).reshape(-1,10)
print(n5)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [184]:
#extracting elements greator than or equal to 90

In [188]:
print("elements >=90:",n5[n5>=90])

elements >=90: [90 91 92 93 94 95 96 97 98 99]


### Key Funtions 
1) np.random.randint(): Generates random integers.
2) np.random.seed(): Sets the random seed for reproducibility.
3) reshape(): Reshapes arrays into specified dimensions.
4) np.arange(): Generates a sequence of numbers.
5) boolean indexing: Allows selection of elements that meet a certain condition.